name: jrladd
markdown: kramdown
safe: true
lsi: false
description: Still learning how to read.
url: http://jrladd.com
permalink: /:title.html

twitter_username:     johnrladd
github_username:      jrladd
instagram_username:    johnrladd
