name: jrladd
markdown: redcarpet
pygments: true
safe: true
lsi: false
description: Still learning how to read.
url: http://jrladd.com
permalink: /:title.html
collections:
    miscellanies:
        output: true
defaults:
    - scope:
        path: ""
        type: miscellanies
      values:
        layout: default